services:
  satquest-backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - breez-data:/data/breez
    networks:
      - satquest-network

  satquest-frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - satquest-backend
    networks:
      - satquest-network

networks:
  satquest-network:
    driver: bridge

volumes:
  breez-data:
