services:
  satquest-backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - satquest-network

  satquest-frontend:
    build: ./frontend
    restart: always
    depends_on:
      - satquest-backend
    ports:
      - "3003:3001"
    networks:
      - satquest-network

networks:
  satquest-network:
    driver: bridge
